name: Update README.md
description: Update the README.md based on the current action's input and outputs
inputs:
  repo-type:
    description: The type of repo to generate documentation for (either workflow or action)
    required: false
    default: "action"
outputs:
  README:
    description: The README.md file for the repository
    value: ${{ steps.publish-readme.outputs.README }}
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
          ref: ${{ github.head_ref }}

    - name: Install dependencies from PSGallery
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module -Name powershell-yaml

    - name: Update README.md
      id: publish-readme
      shell: pwsh
      run: ${{ github.action_path }}/doc-gen.ps1
      env:
        REPO_TYPE: ${{ inputs.repo-type }}

    - name: Push files to repo
      shell: pwsh
      run: |
        # Set the name on the commits as it will appear in Github
        git config --global user.name 'Github Action'
        git config --global user.email 'alwayson@users.noreply.github.com'
        git add README.md
        # Get the name of the commit that triggered the workflow, 
        # so we can refer to it in our automated commit message.
        $message = git log -1 --pretty=format:"%s"

        # Only commit if there are changes to commit, otherwise commit will throw an error.
        if(git status -uno --short) {
        git commit -m "Auto update: $message"

        # push the changes to the current PR
        git push
        } 
        else {
          Write-Output "No changes to commit. Bye."
        }
    
      
