# This workflow file will trigger whenever content.md or header.md has changed. It will then run the doc-gen.ps1 script.
name: Update Docs
on:
  pull_request:
    paths:
      - 'doc-gen/header.md'
      - 'doc-gen/content.md'
      - 'action.yaml'
jobs:

  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            ref: ${{ github.head_ref }}

      - name: Install dependencies from PSGallery
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name powershell-yaml

      - name: Run doc-gen.ps1
        run: ./doc-gen/doc-gen.ps1
        shell: pwsh

      - name: Push files to repo
        shell: pwsh
        run: |
          # Set the name on the commits as it will appear in Github
          git config --global user.name 'Github Action'
          git config --global user.email 'alwayson@users.noreply.github.com'
          git add README.md
          # Get the name of the commit that triggered the workflow, 
          # so we can refer to it in our automated commit message.
          $message = git log -1 --pretty=format:"%s"

          # Only commit if there are changes to commit, otherwise commit will throw an error.
          if(git status -uno --short) {
          git commit -m "Auto update: $message"

          # push the changes to the current PR
          git push
          } 
          else {
            Write-Output "No changes to commit. Bye."
          }

